server:
  port: 8090
spring:
  ################################
  # Redis配置
  ################################
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
  redisson:
    host: redis://127.0.0.1:6379
    connection-timeout: 5000

redisson:

remote:
  config:
    secret: 123456
    clientId: 1212121
    remoteUrl: http://127.0.0.1:8081

breaker:
  maxOpenToTryTime: -1
  maxFailCount: -1
  maxSuccessCount: -1
  maxOpenRetryCount: -1